### ISSUE TITLE
Use to undeclared Type TPKeyboardAvoidingScrollView

### ISSUE THREAD

**Issue by smilydronavalli** [apple-avadhesh/TPKeyboardAvoiding#1]
Hi,

I imported this frame work through pods successfully.But i got the below error
![screen shot 2017-08-08 at 9 13 38 pm](https://user-images.githubusercontent.com/14346725/29080851-8726846c-7c7e-11e7-8465-9a91864bd4ed.png)

Please help it's very important 

Thanks inadvance

**Comment by QiuDaniel** [comment]
same issue

**Comment by tahirbinpasha** [comment]
same issue

**Comment by apple-avadhesh** [comment]
Please update your pod, now the repo is compiled with Xcode 10 and compatible in swift 4.2
