### ISSUE TITLE
Add Swift package Manager Support

### ISSUE THREAD

**Issue by akashnara** [apple-avadhesh/TPKeyboardAvoiding#7]
Add Swift package Manager Support

![Screenshot 2020-03-04 at 12 03 33 PM](https://user-images.githubusercontent.com/61772249/75851491-d20fe980-5e0f-11ea-8ae2-2c78293e8650.png)

**Comment by apple-avadhesh** [comment]
It works but you need to use the branch "master" instead of some version.
